### PR TITLE
Fix the issue of app crash by sending heartbeat regularly

### PR DESCRIPTION
**Pull request by lushan01**
#### Summary

Sending heartbeat package  regularly on the underlying websocket connection to keep the connection alived.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-bot-sample-golang/issues/21

### CODE REVIEW

**Comment by lushan01** [comment]
> Thanks @lushan01 for the pull request!
> 
> Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.
> 
> **Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
> 
> This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.
> 
> Please let us know if you have any questions.
> 
> We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

**Review by hanzei — APPROVED** [review]

**Review by crspeller — APPROVED** [review]
Awesome! Thanks for the contribution @lushan01!

**Comment by jasonblais** [comment]
@DHaussermann Friendly reminder to help with reviews :)

**Comment by DHaussermann** [comment]
@hanzei can you provide any guidance or test steps on this PR? I'm not sure how to validate this with functional testing.

**Comment by hanzei** [comment]
@DHaussermann I did test locally and the websocket persists over time. This is good to merge,

**Pull request merged**
