### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asutosh97**
updated binary name for newer versions

### CODE REVIEW

**Comment by hanzei** [comment]
I'm not sure if this is needed right now. The Mattermost CLI is not going away soon. Why do you want to migrate the README already?

**Comment by asutosh97** [comment]
The command shown in the README was outdated, hence just updated it.

**Comment by hanzei** [comment]
What do you mean with "outdated"? The Mattermost CLI can still be used.

**Comment by hanzei** [comment]
@asutosh97 Would you please update the text to describe a bit more about `mmctl`?

**Comment by jasonblais** [comment]
@hanzei is it sufficient to add a link to the mmctl docs at https://docs.mattermost.com/administration/mmctl-cli-tool.html?

**Comment by hanzei** [comment]
Sure, that would work :+1:

**Comment by jasonblais** [comment]
@hanzei Are you okay merging this PR and then submitting a separate one to add a link to the mmctl docs? 

Don't want to add much more work here given the PR has been open since February.

**Comment by hanzei** [comment]
Sure, we can merge the PR as it is.

**Comment by jasonblais** [comment]
@hanzei Thanks! Are you open to help merge and I can submit a PR to add the link to docs? (I don't have permissions to merge)

**Pull request merged**
