### PR TITLE
Changes so sample bot builds and doesn't get stuck in infinite loop

### PR DESCRIPTION
**Pull request by pneisen**
While experimenting with the sample bot, I first found that the example code no longer compiles against the latest Mattermost go driver. After fixing that up, I found that the sample bot responds to its own "Yes I'm running" message if you check the bot UserId against the one in the event.Broadcast because the event.Broadcast.UserId never gets set. Checking it against the UserId in the post fixes this issue.

### CODE REVIEW

**Comment by annismckenzie** [comment]
I should've looked at the pull requests first – just ran into exactly the same problems. Thanks for pointing out the reason of the infinite loop.

However, this pull request isn't yet complete: if one clones the project and does a `glide install` Glide will fetch the outdated platform models and although the bot will then successfully connect to the channel it won't respond due to the outdated YAML definitions it relies on. Can you do a `glide up` in the project to update the lock file?

**Comment by pneisen** [comment]
Good point! I had done a `glide up`, just didn't check in the glide.lock file. Thanks!

**Comment by hmhealey** [comment]
Thanks for the PR, @pneisen! Sorry, I didn't notice it before I submitted my own PR to support Mattermost 3.5, but your changes to prevent that loop would be really helpful still. Would you mind either rebasing this PR onto master or submitting a new one that just has those changes?

**Comment by pneisen** [comment]
Ok, rebased to your changes. 

I left the new glide.lock in there, because of the comment from @annismckenzie . I think with your changes, a `glide install` will pull down older dependencies.

**Pull request merged**
